### ISSUE TITLE
Too low by 0.5 * binsize

### ISSUE THREAD

**Issue by hcferguson** [pllim/playpen#1]
I've done some tests and I'm virtually certain the routine is returning a value that is too low by `0.5*binsize`.  I put my test at http://nbviewer.jupyter.org/gist/hcferguson/b32c7d3a17a181b1b5e463fc59b02bf0.

**Comment by pllim** [comment]
Huh, maybe somewhere in the code, I mistranslated bin calculations... SPP is 1-indexed, while Python is 0-indexed. I'll investigate. Thanks for the very useful notebook!

**Comment by pllim** [comment]
Possible fix in 3d961058712925f496254a25422c88ee1fd40420

**Comment by pllim** [comment]
You can see your updated notebook at https://github.com/pllim/playpen/blob/master/notebooks/bg_ofilter_harry.ipynb . Although the results from my notebook didn't change much.

**Comment by pllim** [comment]
Also, as you might have noticed, it is very sensitive to `binsize`.

**Comment by pllim** [comment]
Since the sprint is over, I'm closing this.
